webserver:
  image: nginx:latest
  ports:
    - "8080:80"
  volumes:
    - ./code:/code
    - ./nginx.conf:/etc/nginx/conf.d/default.conf
  links:
    - php
    
php:
  # image: php:7.2-fpm
  build: .
  volumes:  
    - ./code:/code
  links:
    - mysql
    - composer

composer:
  image: composer:latest
  command: install
  working_dir: /code
  volumes:
    - ./code:/code
  
mysql:
  image: mysql:5.7
  ports:
    - "3306:3306"
  environment: 
    - MYSQL_ROOT_PASSWORD=password

phpmyadmin:
  image: phpmyadmin/phpmyadmin:latest
  links:
    - mysql:db
  ports:
    - "8082:80"
  environment:
    - PMA_USER=root
    - PMA_PASSWORD=password
    - PHP_UPLOAD_MAX_FILESIZE=100MB
    - PMA_PORT=3306